# Generated by Django 3.1 on 2023-12-09 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Payment_method',
            new_name='payment_method',
        ),
    ]
